export const OPEN_ORDER_STATUSES = [
  "RESERVED", "CONTACT_DETAILS_REVEALED", "SELLER_PREPARING", "READY_FOR_PICKUP",
  "HANDOVER_DECLARED", "BUYER_CONFIRMATION_PENDING", "DISPUTED", "ADMIN_FROZEN"
] as const;
